language: ruby

sudo: false

script: bundle exec rake travis

matrix:
  fast_finish: true
  include:
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-edge
    - rvm: jruby-19mode
    - rvm: jruby-head

  allow_failures:
    - rvm: jruby-head

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false

before_install:
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
